version: "3.4"
services:
  invoiceBe:
    image: invoice_image
    environment:
        - spring.datasource.url=jdbc:mysql://db:3306/invoice
        - spring.secretkey=${secretkey}
        - spring.expiredTime=${expiredTime}
        - spring.datasource.username =${DB_USERNAME}
        - spring.datasource.password =${DB_PASSWORD}
    ports:
      - "8000:8080"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    container_name: mysqldb2
    volumes:
      - .docker/data/db:/data/db
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST= "%"
    ports:
      - "3307:3306"
    restart: always

